# Generated by Django 5.1.1 on 2025-11-01 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chatconversation_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField(help_text='Đoạn text được user chọn để ghi chú')),
                ('note_content', models.TextField(help_text='Ghi chú, cảm nhận của user')),
                ('page_number', models.IntegerField(blank=True, help_text='Số trang', null=True)),
                ('position_start', models.IntegerField(help_text='Vị trí bắt đầu')),
                ('position_end', models.IntegerField(help_text='Vị trí kết thúc')),
                ('color', models.CharField(default='#FFEB3B', help_text='Hex color chosen by frontend (e.g., #FFEB3B)', max_length=7)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page_number', 'position_start'],
                'indexes': [models.Index(fields=['user', 'book'], name='app_booknot_user_id_30a2cf_idx'), models.Index(fields=['book', 'is_public'], name='app_booknot_book_id_8741e1_idx'), models.Index(fields=['page_number'], name='app_booknot_page_nu_8f9189_idx')],
            },
        ),
    ]
